# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Hand-adapted from protoc output for grpclib_ttrpc
"""ttrpc protocol buffer messages: TtrpcStatus, KeyValue, Request, Response."""
from typing import Optional

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

from grpclib.const import Status

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bttrpc.proto\x12\x05ttrpc\",\n\x0bTtrpcStatus\x12\x0c\n\x04\x63'
    b'ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x08'
    b'KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 '
    b'\x01(\t\"t\n\x07Request\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e'
    b'\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c'
    b'\x12\x14\n\x0ctimeout_nano\x18\x04 \x01(\x03\x12!\n\x08metadata\x18'
    b'\x05 \x03(\x0b\x32\x0f.ttrpc.KeyValue\"?\n\x08Response\x12\"\n\x06'
    b'status\x18\x01 \x01(\x0b\x32\x12.ttrpc.TtrpcStatus\x12\x0f\n\x07'
    b'payload\x18\x02 \x01(\x0c\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ttrpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa: E712
    DESCRIPTOR._options = None
    _globals['_TTRPCSTATUS']._serialized_start = 22
    _globals['_TTRPCSTATUS']._serialized_end = 66
    _globals['_KEYVALUE']._serialized_start = 68
    _globals['_KEYVALUE']._serialized_end = 106
    _globals['_REQUEST']._serialized_start = 108
    _globals['_REQUEST']._serialized_end = 224
    _globals['_RESPONSE']._serialized_start = 226
    _globals['_RESPONSE']._serialized_end = 289
# @@protoc_insertion_point(module_scope)


def build_response(
    status: Status,
    message: Optional[str],
    payload: bytes,
) -> bytes:
    """Serialize a ttrpc Response frame payload."""
    ttrpc_status = TtrpcStatus(  # type: ignore[name-defined]  # noqa: F821
        code=status.value,
        message=message or '',
    )
    response = Response(  # type: ignore[name-defined]  # noqa: F821
        status=ttrpc_status,
        payload=payload,
    )
    return response.SerializeToString()
